apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{.Values.branch}}
spec:
  ingressClassName: nginx
  rules:
  - host: {{.Values.clientHost}}
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80