apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.name}}-service
spec:
  selector:
    app: {{.Values.deployment.name}}
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
